language: node_js
node_js:
  - "8.10.0"
branches:
  only:
    - master
script:
  - npm run build
  - npm run test
notifications:
  email:
    recipients:
      - exhikkii@gmail.com
    on_success: always
    on_failure: always
